version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18 
    commands:
      - echo Installing source NPM dependencies...
      - npm install
build:
  commands:
    - echo Building the application...
    - npm install  # Ensure all dependencies are installed
    - echo Dummy build step to complete the build phase
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  name: beREELv2-2
  files:
    - dist/**/*
    - public/**/* 

